name: lint

on: [push]

env:
  CI: true

jobs:
  run-linters:
    name: run linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci --no-optional
      - uses: wearerequired/lint-action@v1
        with:
          eslint: true
