name: test

on: [push]

env:
  CI: true

jobs:
  build:
    name: nodejs
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [10.x, 12.x, 14.x, 15.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
        cache: 'npm'
    - run: npm ci --no-production
    - run: npm test
    - uses: vebr/jest-lcov-reporter@v0.2.1
      if: matrix.node == '10.x'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: ./coverage/lcov.info
        update-comment: true
